// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdYbVu26kRyjzyEvnoQQfLchO-x6D0pBk',
    appId: '1:50252869733:web:7a5a5033e36b67dff9968c',
    messagingSenderId: '50252869733',
    projectId: 'irlapp-b76f8',
    authDomain: 'irlapp-b76f8.firebaseapp.com',
    storageBucket: 'irlapp-b76f8.appspot.com',
    measurementId: 'G-D45B6NG0S1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZoSOylOMbaKiWyZ6LMEmhmbZXtJaqHJw',
    appId: '1:50252869733:android:80dae1cce35fb9d8f9968c',
    messagingSenderId: '50252869733',
    projectId: 'irlapp-b76f8',
    storageBucket: 'irlapp-b76f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABBJ4l98pFAgqorLMYkzqx7XaBl0-9vvA',
    appId: '1:50252869733:ios:2a98299ed197699cf9968c',
    messagingSenderId: '50252869733',
    projectId: 'irlapp-b76f8',
    storageBucket: 'irlapp-b76f8.appspot.com',
    iosBundleId: 'com.example.irl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABBJ4l98pFAgqorLMYkzqx7XaBl0-9vvA',
    appId: '1:50252869733:ios:fdcee0ad824539cdf9968c',
    messagingSenderId: '50252869733',
    projectId: 'irlapp-b76f8',
    storageBucket: 'irlapp-b76f8.appspot.com',
    iosBundleId: 'com.example.irl.RunnerTests',
  );
}
